apiVersion: apps/v1
kind: Deployment
metadata:
name: php_simple_curd
labels:
  app: php_simple_curd
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: php_simple_curd
      tier: php_simple_curd
  spec:
    containers:
    - name: php_simple_curd
      image: danztensai123/php_simple_curd:tagname
      imagePullPolicy: Always
      ports:
      - containerPort: 80
        name: php_simple_curd

---
apiVersion: v1
kind: Service
metadata:
name: php_simple_curd
labels:
  app: php_simple_curd
spec:
ports:
  - port: 80
    targetPort: 80
selector:
  app: php_simple_curd
  tier: php_simple_curd
type: LoadBalancer